### ISSUE TITLE
Suggestion for translation of Amplifabricator

### ISSUE THREAD

**Issue by 3TUSK** [InfinityStudio/Gregtech5-Translation-Chinese#59]
Hey, I do think Amplifabricator should not be translated into "放大器", cause some there are players who are confused about what it is for. (although some of them can get NEI to search)
Actually "ampli" does have the meaning of "放大"
I have an idea, that is "增幅液体制造器" (based on a gt5 tutorial), but it is too long.
I don't know if there is another possibility. Then i submit this issue.
btw, this translation is out of date, would you guys mind to update it
(like sifing machine, arc furnace, etc.)

**Comment by TehporP** [comment]
说真的你可以说中文的..
因为学业   暂时没太多时间去更新
这周我看看能不能做的到
尽量
还有你的译名不错  将在更新后加入

**Comment by DeckerCHAN** [comment]
Thank you for your notice!
Well, the situation for me seems like a little bit sophisticated. I have to set the highest priority on my study rather on this work. Hope you could understand :-)
But, there still some good news: I would finish my study and work around this task as fast as possible, just recently! A new mechanism which focus on simplify translate procedure had already been added.(pls checkout the development branch)
Plus, your suggestion would be review and consider.

**Comment by 3TUSK** [comment]
Forgot to close it? But sometimes I have OCD.
